# node 22
FROM node:22-alpine

# 作業ディレクトリ
WORKDIR /app

# package.json をコピーして依存関係インストール
COPY package*.json ./
RUN npm install --no-optional

# ソースコードをすべてコピー
COPY . .

# 開発サーバー用のポートを開ける
EXPOSE 5173

# SvelteKit開発サーバーを起動
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
