FROM node:22-alpine AS build

WORKDIR /app

# 依存関係のインストールとビルド
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# 単一ステージに変更
FROM alpine:latest

WORKDIR /dist
# ボリュームが既存の場合、まず中身を空にする
RUN rm -rf /dist/* || true
# ビルド成果物をコピー
COPY --from=build /app/build/* /dist/

# このコンテナはビルドのみを行うので終了
CMD ["true"]
