# Python 3.9
FROM python:3.9-slim

# 作業ディレクトリを /code に設定
WORKDIR /code

# 依存関係をインストール
COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# ソースコードをすべて /code/app にコピー
COPY ./app /code/app
COPY ./alembic /code/alembic
COPY ./alembic.ini /code/alembic.ini

# ポートを開ける
EXPOSE 8000

# サーバー起動コマンドを指定
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]