version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/inventory_db

  db:
    image: postgres:15
    container_name: postgres-db-prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - dbdata-prod:/var/lib/postgresql/data

volumes:
  dbdata-prod:
