version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/inventory_db

  db:
    image: postgres:15
    container_name: postgres-db-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - dbdata-dev:/var/lib/postgresql/data

volumes:
  dbdata-dev:
