# 開発環境をオーバーライド
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - '5173:5173'
    volumes:
      - ../frontend:/app
      - /app/node_modules

  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    volumes:
      - ../backend/app:/code/app
      - ../backend/alembic:/code/alembic
      - ../backend/alembic.ini:/code/alembic.ini
      - ../backend/insert_samples.py:/code/insert_samples.py
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/inventory_db
      - DEBUG=true
    env_file:
      - ../backend/.env.dev
    command: >
      sh -c "
        sleep 2 &&
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  db:
    container_name: postgres-db-dev
    volumes:
      - dbdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  dbdata-dev:
