# 開発環境をオーバーライド
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - '5173:5173'
    volumes:
      - ../frontend:/app
      - /app/node_modules
    env_file:
      - ../frontend/.env.dev

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - '8000:8000'
    volumes:
      - ../backend/app:/code/app
      - ../backend/alembic:/code/alembic
      - ../backend/alembic.ini:/code/alembic.ini
      - ../backend/insert_samples.py:/code/insert_samples.py
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../backend/.env.dev
    command: >
      sh -c "
        sleep 2 &&
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  db:
    image: postgres:15
    container_name: postgres-db-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - dbdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  dbdata-dev:
    name: inventory-dbdata-dev
