services:
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy-prod
    ports:
      - '0.0.0.0:8080:80'
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    volumes:
      - frontend_build:/dist
    env_file:
      - ../frontend/.env.prod
    # フロントエンドはビルドのみを担当し、Nginxが配信するので直接公開はしない

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    ports:
      - '0.0.0.0:8000:8000'
    depends_on:
      - db
    env_file:
      - ../backend/.env.prod
    restart: always
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: postgres:15
    container_name: postgres-db-prod
    ports:
      - '0.0.0.0:5433:5432' # 開発環境と競合しないようにホスト側のポートを変更
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - dbdata-prod:/var/lib/postgresql/data
    restart: always

volumes:
  dbdata-prod:
    name: inventory-dbdata-prod
  frontend_build:
    name: frontend-build-prod
