services:
  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/inventory_db
      - DEBUG=false
    restart: always
    env_file:
      - ../backend/.env.prod

  db:
    image: postgres:15
    container_name: postgres-db-prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - dbdata-prod:/var/lib/postgresql/data

volumes:
  dbdata-prod:
