"""Initial migration

Revision ID: 1bd1c7c8265b
Revises: 9356b24f2137
Create Date: 2025-03-12 15:06:41.300459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd1c7c8265b'
down_revision = '9356b24f2137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 