name: Deploy to Mini PC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env.prod files
        run: |
          echo "${{ secrets.ENV_PROD_BACKEND }}" > backend/.env.prod
          echo "${{ secrets.ENV_PROD_FRONTEND }}" > frontend/.env.prod
          ls -la backend/.env.prod
          ls -la frontend/.env.prod

      - name: Clean Docker resources
        run: |
          docker builder prune -af
          docker system prune -af --volumes
          docker volume rm frontend-build-prod || true
          docker volume rm backend-build-prod || true

      - name: Build and deploy
        run: |
          cd infra
          docker compose down
          docker compose -f docker-compose.yml build --no-cache
          docker compose -f docker-compose.yml up -d
